name: "Build on PR or Dev"

on:
  pull_request:
    branches:
      - dev
      - test
      
  push:
    branches:
      - dev

jobs:  
  build:      
    name: Build & Release 
    runs-on: ubuntu-latest
    
    defaults:
        run: 
          working-directory: brightimpact_user_app

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Setup Java
      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'

      # 3. Setup Flutter
      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: 'stable'

      # 4. Install Dependencies
      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./brightimpact_user_app

      # 5. Setup Keystore
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
          
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties

      # 6. Building APK
      - name: Build APK
        run: flutter build apk --release
        working-directory: ./brightimpact_user_app

      # 7. Building App Bundle (AAB)
      - name: Build App Bundle
        run: flutter build appbundle
        working-directory: ./brightimpact_user_app

      # 8. Build IPA (iOS Build)
     # - name: Build IPA
      #  run: flutter build ipa --no-codesign
       # working-directory: ./brightimpact_user_app

      # 9. Compress Archives and IPAs
     # - name: Compress Archives and IPAs
      #  run: |
       #   cd build
        #  tar -czf ios_build.tar.gz ios

      

